using Microsoft.EntityFrameworkCore.Migrations;

namespace CheaplayMVC.Migrations
{
    public partial class MakeAutogeneratedIdForUpdatesTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
